-- 086_household.sql — Multi-tenant Phase 1 (a): household table + household_id on every tenant table.
-- ADDITIVE + INERT. Constant DEFAULT 1 => instant fast-default (no table rewrite), all existing
-- rows land in household 1, so single-household installs (dev / prod / self-hosted) are byte-identical.
-- RLS is NOT enabled here (that is the demo-only activation step). Demo inserts get the right
-- household via a per-column default set at activation; here the default is a plain constant.
CREATE TABLE IF NOT EXISTS household (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT NOT NULL DEFAULT 'Haushalt',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO household (id, name) VALUES (1, 'Haushalt') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('household','id'), GREATEST((SELECT MAX(id) FROM household), 1));

ALTER TABLE users ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE users ADD CONSTRAINT users_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_users_household ON users (household_id);
ALTER TABLE konto ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE konto ADD CONSTRAINT konto_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_konto_household ON konto (household_id);
ALTER TABLE family_member ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE family_member ADD CONSTRAINT family_member_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_family_member_household ON family_member (household_id);
ALTER TABLE einkauf ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE einkauf ADD CONSTRAINT einkauf_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_einkauf_household ON einkauf (household_id);
ALTER TABLE artikel ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE artikel ADD CONSTRAINT artikel_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_artikel_household ON artikel (household_id);
ALTER TABLE artikel_consumer ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE artikel_consumer ADD CONSTRAINT artikel_consumer_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_artikel_consumer_household ON artikel_consumer (household_id);
ALTER TABLE artikel_ausschluss ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE artikel_ausschluss ADD CONSTRAINT artikel_ausschluss_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_artikel_ausschluss_household ON artikel_ausschluss (household_id);
ALTER TABLE auth_token ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE auth_token ADD CONSTRAINT auth_token_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_auth_token_household ON auth_token (household_id);
ALTER TABLE bank_match_suggestion ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE bank_match_suggestion ADD CONSTRAINT bank_match_suggestion_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_bank_match_suggestion_household ON bank_match_suggestion (household_id);
ALTER TABLE bank_tx ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE bank_tx ADD CONSTRAINT bank_tx_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_bank_tx_household ON bank_tx (household_id);
ALTER TABLE budget ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE budget ADD CONSTRAINT budget_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_budget_household ON budget (household_id);
ALTER TABLE budget_category ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE budget_category ADD CONSTRAINT budget_category_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_budget_category_household ON budget_category (household_id);
ALTER TABLE canonical_alias ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE canonical_alias ADD CONSTRAINT canonical_alias_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_canonical_alias_household ON canonical_alias (household_id);
ALTER TABLE canonical_consumer ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE canonical_consumer ADD CONSTRAINT canonical_consumer_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_canonical_consumer_household ON canonical_consumer (household_id);
ALTER TABLE canonical_meta ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE canonical_meta ADD CONSTRAINT canonical_meta_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_canonical_meta_household ON canonical_meta (household_id);
ALTER TABLE canonical_translation ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE canonical_translation ADD CONSTRAINT canonical_translation_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_canonical_translation_household ON canonical_translation (household_id);
ALTER TABLE category ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE category ADD CONSTRAINT category_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_category_household ON category (household_id);
ALTER TABLE einkaufsliste ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE einkaufsliste ADD CONSTRAINT einkaufsliste_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_einkaufsliste_household ON einkaufsliste (household_id);
ALTER TABLE einkaufsliste_item ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE einkaufsliste_item ADD CONSTRAINT einkaufsliste_item_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_einkaufsliste_item_household ON einkaufsliste_item (household_id);
ALTER TABLE email_message ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE email_message ADD CONSTRAINT email_message_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_email_message_household ON email_message (household_id);
ALTER TABLE fixed_cost ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE fixed_cost ADD CONSTRAINT fixed_cost_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_fixed_cost_household ON fixed_cost (household_id);
ALTER TABLE fixed_cost_check ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE fixed_cost_check ADD CONSTRAINT fixed_cost_check_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_fixed_cost_check_household ON fixed_cost_check (household_id);
ALTER TABLE imported_email ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE imported_email ADD CONSTRAINT imported_email_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_imported_email_household ON imported_email (household_id);
ALTER TABLE imported_file ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE imported_file ADD CONSTRAINT imported_file_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_imported_file_household ON imported_file (household_id);
ALTER TABLE income ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE income ADD CONSTRAINT income_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_income_household ON income (household_id);
ALTER TABLE merchant_konto ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE merchant_konto ADD CONSTRAINT merchant_konto_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_merchant_konto_household ON merchant_konto (household_id);
ALTER TABLE nlanalytics_log ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE nlanalytics_log ADD CONSTRAINT nlanalytics_log_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_nlanalytics_log_household ON nlanalytics_log (household_id);
ALTER TABLE notification ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE notification ADD CONSTRAINT notification_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_notification_household ON notification (household_id);
ALTER TABLE offer ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE offer ADD CONSTRAINT offer_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_offer_household ON offer (household_id);
ALTER TABLE offer_subscription ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE offer_subscription ADD CONSTRAINT offer_subscription_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_offer_subscription_household ON offer_subscription (household_id);
ALTER TABLE push_subscription ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE push_subscription ADD CONSTRAINT push_subscription_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_push_subscription_household ON push_subscription (household_id);
ALTER TABLE rejected_proposal ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE rejected_proposal ADD CONSTRAINT rejected_proposal_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_rejected_proposal_household ON rejected_proposal (household_id);
ALTER TABLE reserve_charge ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE reserve_charge ADD CONSTRAINT reserve_charge_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_reserve_charge_household ON reserve_charge (household_id);
ALTER TABLE shopping_list ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE shopping_list ADD CONSTRAINT shopping_list_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_shopping_list_household ON shopping_list (household_id);
ALTER TABLE shopping_session ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE shopping_session ADD CONSTRAINT shopping_session_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_shopping_session_household ON shopping_session (household_id);
ALTER TABLE spending_goal ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE spending_goal ADD CONSTRAINT spending_goal_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_spending_goal_household ON spending_goal (household_id);
ALTER TABLE store_branch ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE store_branch ADD CONSTRAINT store_branch_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_store_branch_household ON store_branch (household_id);
ALTER TABLE user_mailbox ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE user_mailbox ADD CONSTRAINT user_mailbox_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_user_mailbox_household ON user_mailbox (household_id);
ALTER TABLE verifikations_queue ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE verifikations_queue ADD CONSTRAINT verifikations_queue_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_verifikations_queue_household ON verifikations_queue (household_id);
ALTER TABLE vorrat_override ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE vorrat_override ADD CONSTRAINT vorrat_override_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_vorrat_override_household ON vorrat_override (household_id);
ALTER TABLE vorschlag_snooze ADD COLUMN IF NOT EXISTS household_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE vorschlag_snooze ADD CONSTRAINT vorschlag_snooze_household_fk FOREIGN KEY (household_id) REFERENCES household(id);
CREATE INDEX IF NOT EXISTS ix_vorschlag_snooze_household ON vorschlag_snooze (household_id);
